### PR TITLE
Migrated to Android X

### PR DESCRIPTION
**Pull request by way2jatin**
In order to use this library in today's day and age, we need to make sure the given library is compatible with AndroidX as i myself couldn't integrate the same in my project. Hope this is good for you guys.

### CODE REVIEW

**Review by tarunnickelfox — APPROVED** [review]

**Comment by edsilfer** [comment]
Could you please exclude the changes in `.idea` dir from the PR? We should have 

```
.idea/**/gradle.xml
.idea/**/libraries
```

In `.gitignore`

**Comment by way2jatin** [comment]
@edsilfer I have updated gitignore and then removed untracked files as well. I hope this solved our purpose.

**Review by edsilfer — APPROVED** [review]

**Comment by way2jatin** [comment]
@edsilfer Thanks for the review. I think you need to update the library from the-big-refactor branch in order for new projects to use it.

**Comment by edsilfer** [comment]
> @edsilfer Thanks for the review. I think you need to update the library from the-big-refactor branch in order for new projects to use it.

The PR was merged in master yesterday :)

**Pull request merged**
